### ISSUE TITLE
brew 1.0.0.7 upgrade failure

### ISSUE THREAD

**Issue by chenrui333** [create-dmg/create-dmg#92] opened 2020-03-07 18:54 UTC
relates to https://github.com/Homebrew/homebrew-core/pull/45310, https://github.com/Homebrew/homebrew-core/pull/50981

local test failure:

```
$ brew test create-dmg
Testing create-dmg
==> /usr/local/Cellar/create-dmg/1.0.0.7/bin/create-dmg --sandbox-safe --eula /private/tm
Last 15 lines from /Users/ruichen/Library/Logs/Homebrew/create-dmg/test.01.create-dmg:
Reading Apple (Apple_partition_map : 1)…
Reading DiscRecording 9.0.3d5 (Apple_HFS : 2)…
Reading  (Apple_Free : 3)…
Elapsed Time:   3.380ms
Speed: 260.0Mbytes/sec
Savings: 0.0%
created: /private/tmp/create-dmg-test-20200307-78550-hqrblp/rw.Brew-Test.dmg
Mounting disk image...
Unmounting disk image...
Mount directory: /Volumes/Brew-Test
Device name:     /dev/disk2
Running Applescript: /usr/bin/osascript "/var/folders/cb/s5w4_0p50639mbdvqhnmf7wm0000gn/T/createdmg.tmp.XXXXXXXXXX.EvLGx6N1" "Brew-Test"
/var/folders/cb/s5w4_0p50639mbdvqhnmf7wm0000gn/T/createdmg.tmp.XXXXXXXXXX.EvLGx6N1:85:89: execution error: Finder got an error: A privilege violation occurred. (-10004)
Failed running AppleScript
"disk2" ejected.
Error: create-dmg: failed
```

**Comment by apjanke** [comment] 2020-05-29 03:31
I've created [a new `create-dmg/create-dmg` custom tap](https://github.com/create-dmg/homebrew-create-dmg) with a formula for the new create-dmg so we can work on this before submitting it to Homebrew.

I can reproduce a similar error when installing from `--HEAD`:
```
[Formula] $ pwd
/usr/local/Homebrew/Library/Taps/create-dmg/homebrew-create-dmg/Formula
[Formula] $ brew install --HEAD create-dmg/create-dmg/create-dmg
==> Installing create-dmg from create-dmg/create-dmg
==> Cloning https://github.com/create-dmg/create-dmg.git
Updating /Users/janke/Library/Caches/Homebrew/create-dmg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 7b6955e Disable tests/ in install because apparently we don't have any yet?
==> make install prefix=/usr/local/Cellar/create-dmg/HEAD-7b6955e
🍺  /usr/local/Cellar/create-dmg/HEAD-7b6955e: 10 files, 62.4KB, built in 4 seconds
[Formula] $ brew test create-dmg
Testing create-dmg/create-dmg/create-dmg
==> /usr/local/Cellar/create-dmg/HEAD-7b6955e/bin/create-dmg --sandbox-safe --eula /private/tmp/create-dmg-test-20200528-3972-1mtn3xu/Brew-Eula.txt /private/tmp/create-dmg-test-20
Last 15 lines from /Users/janke/Library/Logs/Homebrew/create-dmg/test.01.create-dmg:
Reading Apple (Apple_partition_map : 1)…
Reading DiscRecording 9.0.3d5 (Apple_HFS : 2)…
Reading  (Apple_Free : 3)…
Elapsed Time:   8.047ms
Speed: 109.2Mbytes/sec
Savings: 0.0%
created: /private/tmp/create-dmg-test-20200528-3972-1mtn3xu/rw.Brew-Test.dmg
Mounting disk image...
Unmounting disk image...
Mount directory: /Volumes/Brew-Test
Device name:     /dev/disk3
Running AppleScript: /usr/bin/osascript "/var/folders/_4/9mx5ryp52bb_z6drbcbrhwl40000gn/T/createdmg.tmp.XXXXXXXXXX.vNylqITG" "Brew-Test"
/var/folders/_4/9mx5ryp52bb_z6drbcbrhwl40000gn/T/createdmg.tmp.XXXXXXXXXX.vNylqITG:85:89: execution error: Finder got an error: A privilege violation occurred. (-10004)
Failed running AppleScript
"disk3" ejected.
Error: create-dmg/create-dmg/create-dmg: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/create-dmg/HEAD-7b6955e/bin/create-dmg --sandbox-safe --eula /private/tmp/create-dmg-test-20200528-3972-1mtn3xu/Brew-Eula.txt /private/tmp/create-dmg-test-20200528-3972-1mtn3xu/Brew-Test.dmg /private/tmp/create-dmg-test-20200528-3972-1mtn3xu/Test-Source
/usr/local/Homebrew/Library/Homebrew/formula.rb:2013:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `system'
/usr/local/Homebrew/Library/Taps/create-dmg/homebrew-create-dmg/Formula/create-dmg.rb:23:in `block in <class:CreateDmg>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1821:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1820:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:888:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1819:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2063:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2062:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1813:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'
[Formula] $
```

Looks like a sandboxing issue. This is on macOS 10.14.6.

**Comment by apjanke** [comment] 2020-05-29 03:48
Fixed in https://github.com/create-dmg/create-dmg/commit/f76ddf5665969168c8848ee189d50024fd33a421 and https://github.com/create-dmg/create-dmg/commit/2b1436dada08fb72414ba48c4bb67ab98a7ae9d3, I think. Works for me locally now:

```
[Formula] $ brew install --HEAD create-dmg/create-dmg/create-dmg
==> Installing create-dmg from create-dmg/create-dmg
==> Cloning https://github.com/create-dmg/create-dmg.git
Updating /Users/janke/Library/Caches/Homebrew/create-dmg--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 2b1436d Use xcode-select to locate Rez by default
==> make install prefix=/usr/local/Cellar/create-dmg/HEAD-2b1436d
🍺  /usr/local/Cellar/create-dmg/HEAD-2b1436d: 10 files, 62.8KB, built in 3 seconds
[Formula] $ brew test create-dmg
Testing create-dmg/create-dmg/create-dmg
==> /usr/local/Cellar/create-dmg/HEAD-2b1436d/bin/create-dmg --sandbox-safe --eula /private/tmp/create-dmg-test-20200528-8667-jw4a2w/Brew-Eula.txt /private/tmp/create-dmg-test-202
[Formula] $
```

**Comment by apjanke** [comment] 2020-05-29 04:13
Since self-submission is discouraged by Homebrew, I've asked on the #machomebrew channel on Freenode IRC if someone can have a look at my new 1.0.8 release and do a PR for getting that in to core Homebrew.

**Comment by apjanke** [comment] 2020-05-29 04:30
Created a version bump PR in core Homebrew for the new 1.0.8 release: https://github.com/Homebrew/homebrew-core/pull/55413. I think this one will work.

**Comment by apjanke** [comment] 2020-05-29 06:13
1.0.8 has been accepted by Homebrew core: https://github.com/Homebrew/homebrew-core/commit/2c1b1ab476ddbc04ad7c6ed6cdc3362280b063ed.

This is fixed.

**Closed by apjanke** 2020-05-29 06:13 UTC
Labels: bug, packaging
