### ISSUE TITLE
timeout for DiskArbitration expired

### ISSUE THREAD

**Issue by theDevelopper** [create-dmg/create-dmg#74] opened 2018-12-20 08:20 UTC
Since a couple days I almost always (like 4 out of 5 times) get an error

```
Done running the applescript...
Fixing permissions...
Done fixing permissions.
Blessing started
Blessing finished
Unmounting disk image...
hdiutil: detach: timeout for DiskArbitration expired
hdiutil: detach: drive not detached
```

I am running the script via Jenkins on latest Mojave. The errors suddenly popped up without changing anything, but now is quite persistent and killing almost all builds.

**Comment by aonez** [comment] 2018-12-21 08:49
Maybe you've installed something that monitors volumes? So the mounted DMG can't be unmounted?

**Comment by theDevelopper** [comment] 2018-12-21 09:45
no. its a simple old mac mini with a clean install and xcode. it is used only as a build server. So no user activity. It worked fine for 5 month and started acting up last week without any changes to the  setup.

**Comment by apjanke** [comment] 2020-05-29 06:33
I recently made the disk-unmounting process more conservative, so that it only tries the unmount if there really is a leftover mounted image: https://github.com/create-dmg/create-dmg/commit/867ee5591bf175339e6610464808882475deb18d.

I'm thinking this will fix the issue, and since this issue is over a year old, closing it out as "cannot reproduce". If anyone is still experiencing this problem with the current `create-dmg` code, please re-open.

**Closed by apjanke** 2020-05-29 06:33 UTC
Labels: bug

**Comment by markotoplak** [comment] 2022-04-29 12:30
Hi @apjanke, I could quite reliable replicate the bug with Orange builds on Appveyor. Likely the problem there is the sheer size of the DMG - it is about 300MB. 

Some failed builds can be seen in [this repo](https://github.com/ales-erjavec/orange3-installers), for example here: https://github.com/ales-erjavec/orange3-installers/commit/dc2941885a7e49e86c532c81bb9cd2656a2271e7

Modifying the script so that `MAXIMUM_UNMOUNTING_ATTEMPTS=6` is set does help. Could you perhaps consider making this a parameter or perhaps just increase its default value? Even setting it to 6 would mean at most 64+32+16+8+4+2+1 seconds of maximum wait time.

**Comment by apjanke** [comment] 2022-05-02 01:20
Yeah, this sounds like a good candidate for a parameter, and probably also increasing its default value. create-dmg is generally only used in build situations, so spending some extra time isn't a terrible outcome, and I don't unmount failures are super common anyway.

I'm pretty slammed at work lately but this is a small change so I'll try to get to it soon.

@markotoplak  Would you mind [submitting a separate Issue for this](https://github.com/create-dmg/create-dmg/issues/new) so we don't have to reopen this old issue and spam the other participants who aren't interested in this particular case?
